=== vchacal327/VictorChacon_UD4_LMSGI/Librería/Catalogo.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="catalogo">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="libro" maxOccurs="10">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="titulo"/>
              <xs:element name="autor">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="nombre"/>
                    <xs:element type="xs:string" name="apellidos"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element type="xs:string" name="genero"/>
              <xs:element type="xs:string" name="editorial"/>
              <xs:element type="xs:date" name="fecha"/>
              <xs:element type="xs:string" name="ISBN"/>
              <xs:element type="xs:integer" name="nPaginas"/>
              <xs:element type="xs:string" name="descripcion"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== vchacal327/VictorChacon_UD4_LMSGI/Librería/Catalogo_X.xml
<<<<<<< HEAD
<?xml version="1.0" encoding="UTF-8"?>
<catalogo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Catalogo.xsd">
    <libro>
        <titulo>Don Quijote de la Mancha</titulo>
        <autor>
            <nombre>Miguel</nombre>
            <apellidos>De Cervantes Saavedra</apellidos>
        </autor>
        <genero>Novela</genero>
        <editorial>RAE</editorial>
        <fecha>2015-09-10</fecha>
        <ISBN>978-8420412146</ISBN>
        <nPaginas>1376</nPaginas>
        <descripcion>En 2004 y coincidiendo con la celebración del IV Centenario de la publicación de la primera parte de Don Quijote de la Mancha, la Real Academia Española y la Asociación de Academias de la Lengua Española dieron inicio a un proyecto de edición de grandes obras de la literatura en español. Concebida como una línea de ediciones conmemorativas ocasionales y de circulación limitada de los grandes clásicos hispanos de todos los tiempos, dichas obras son publicadas y distribuidas en todo el mundo de habla hispana. Esta reedición de Don Quijote de la Macha con ocasión del IV centenario de Cervantes se une ahora a esta colección de la que ya forman parte Rubén Darío. Del símbolo a la realidad; Cien años de soledad de Gabriel García Márquez; La región más transparente, de Carlos Fuentes; Antología general, de Pablo Neruda ; Gabriela Mistral en verso y prosa, una antología de la autora; La ciudad y los perros de Mario Vargas Llosa y La colmena, de Camilo José Cela.</descripcion>
    </libro>
    <libro>
        <titulo>El Camino</titulo>
        <autor>
            <nombre>Miguel</nombre>
            <apellidos>Delibes Setién</apellidos>
        </autor>
        <genero>Novela</genero>
        <editorial>Austral</editorial>
        <fecha>2022-05-18</fecha>
        <ISBN>978-8423361519</ISBN>
        <nPaginas>208</nPaginas>
        <descripcion>Daniel el Mochuelo intuye a sus once años que su camino está en la aldea, junto a sus amigos, sus gentes y sus pájaros. Pero su padre quiere que vaya a la ciudad a estudiar el bachillerato. A lo largo de la noche que precede a la partida, Daniel, insomne, con un nudo en la garganta, evocará sus correrías con sus amigos ―Roque el Moñigo y Germán el Tiñoso― a través de los campos descubriendo el cielo y la tierra, y revivirá las andanzas de la gente sencilla de la aldea. La simpatía humana con que esa mirada infantil nos introduce en el pueblo, haciéndonos conocer toda una impresionante galería de tipos, y la fuerza con que a través de rasgos frecuentemente caricaturescos se nos presentan siempre netos y vivos son dos de los mayores aciertos de esta novela.
            
        Feliz evocación de un tiempo cuyo encanto y fascinación advertimos cuando ya se nos ha escapado de entre los dedos, El camino es, por su amalgama de nitidez realista, humor sutil, nostalgia contenida e irisación poética, no sólo una de las mejores novelas de Miguel Delibes, sino también, como señala la crítica, «una de las obras maestras de la narrativa contemporánea».
        </descripcion>
    </libro>
    <libro>
        <titulo>Fortunata y Jacinta</titulo>
        <autor>
            <nombre>Benito</nombre>
            <apellidos>Pérez Galdós</apellidos>
        </autor>
        <genero>Novela</genero>
        <editorial>Espasa</editorial>
        <fecha>2020-01-28</fecha>
        <ISBN>978-8467029284</ISBN>
        <nPaginas>896</nPaginas>
        <descripcion>La tormentosa relación amorosa entre los dos protagonistas, Juanito Santa Cruz y Fortunata, incapaces de superar las dificultades que su diferencia de estatus social les impone, se desarrolla en el ambiente castizo de finales del siglo xix, presentándose, además, un panorama completísimo de la vida y actividades de la clase media española.
            Asimismo, el libro retrata de forma magistral el papel de la mujer en la sociedad, con Fortunata y Jacinta como máximas exponentes, y la hipocresía dominante en una burguesía que intenta superar su anquilosamiento, impregnada de una religiosidad asfixiante y de unas costumbres firmemente arraigadas.</descripcion>
    </libro>
    <libro>
        <titulo>La Celestina</titulo>
        <autor>
            <nombre>Fernando</nombre>
            <apellidos>De Rojas </apellidos>
        </autor>
        <genero>Teatro</genero>
        <editorial>Anaya</editorial>
        <fecha>2017-04-27</fecha>
        <ISBN>978-8467871319</ISBN>
        <nPaginas>448</nPaginas>
        <descripcion>La Celestina es una de las obras más complejas de toda nuestra literatura clásica. Su éxito inmediato produjo la sucesión ininterrumpida de ediciones y la pronta traducción a otras lenguas a principios del siglo XVI (italiano, alemán, francés). Se ha convertido en una genial aportación de la literatura española a la literatura universal, porque retrata pasiones humanas elementales y no ha perdido nunca actualidad. Al margen del envoltorio lingüístico, al margen de los cambios en lo exterior, al margen incluso de la intención del autor, los seres humanos comprendemos a través de ella lo más íntimo de nuestras debilidades, que son las mismas que hace quinientos años.</descripcion>
    </libro>
    <libro>
        <titulo>La Regenta</titulo>
        <autor>
            <nombre>Leopoldo Enrique</nombre>
            <apellidos>García-Alas y Ureña</apellidos>
        </autor>
        <genero>Novela</genero>
        <editorial>Alba Editorial</editorial>
        <fecha>2022-02-16</fecha>
        <ISBN>978-8490658406</ISBN>
        <nPaginas>896</nPaginas>
        <descripcion>Por encima de su formidable galería de personajes, es la ciudad de Vetusta, trasunto inequívoco de Oviedo–donde Clarín pasó buena parte de su vida–, la auténtica protagonista de La Regenta (1884-1885), que aquí recuperamos en edición de Ignacio Echevarría. En ella se asiste al implacable cerco que, al amparo de la hipocresía reinante, tienden a Ana Ozores, la Regenta–una joven belleza llena de fantasías románticas, casada con un hombre mayor que no satisface sus ansias de amor–, un petimetre local, envanecido de su bien labrada reputación de donjuán, y el ambicioso sacerdote destinado a ejercer de su director espiritual y a enamorarse perdidamente de ella.</descripcion>
    </libro>
    <libro>
        <titulo>Lazarillo de Tormes</titulo>
        <autor>
            <nombre></nombre>
            <apellidos></apellidos>
        </autor>
        <genero>Novela</genero>
        <editorial>Penguin Clásicos</editorial>
        <fecha>2022-01-03</fecha>
        <ISBN>978-8491050292</ISBN>
        <nPaginas>176</nPaginas>
        <descripcion>El Lazarillo de Tormes inauguró el género de la novela picaresca. Relata las desventuras que un joven de origen humilde sufre al servicio de sus amos, entre los que se cuentan un ciego, un clérigo y un hidalgo pobre. Los avatares por los que pasa Lázaro son un magnífico pretexto para plasmar una ácida crítica a la sociedad de la época. Asimismo, el tratamiento de la anécdota, el lenguaje sobrio y eficaz, y una nueva concepción en el uso de los personajes propiciaron una renovación en la literatura del momento.
            
            Esta edición incluye una introducción que contextualiza la obra, un aparato de notas, una cronología y una bibliografía esencial, así como propuestas para fomentar el debate en torno a la lectura. Está al cuidado de Florencio Sevilla, catedrático de literatura española de la Universidad Autónoma de Madrid.</descripcion>
    </libro>
    <libro>
        <titulo>Los pazos de Ulloa</titulo>
        <autor>
            <nombre>Emilia</nombre>
            <apellidos>Pardo Bazán</apellidos>
        </autor>
        <genero>Novela</genero>
        <editorial>Alianza</editorial>
        <fecha>2020-10-29</fecha>
        <ISBN>978-8413620947</ISBN>
        <nPaginas>640</nPaginas>
        <descripcion>Cuando el joven sacerdote don Julián se presenta en la hacienda de los Pazos de Ulloa, en la Galicia rural, para ejercer de administrador, contra lo que cabría esperar del nombre del lugar y de las resonancias del marquesado de Ulloa, el mundo con el que se halla está lejos de cualquier grandeza y, en cuanto a los mecanismos y pasiones que en él rigen, próximo a un primitivismo medieval. Las figuras del sobrevenido marqués don Pedro, del malicioso mayordomo Primitivo y de su hija Sabel, consciente de las armas de su sexo, son el punto de partida de un relato en el cual palpitan el atraso y la decadencia, las ambiciones y el aislamiento, el instinto frente a la sociedad, la inanidad de la nobleza frente a la férrea determinación del aldeano y, finalmente, el enfrentamiento entre la atracción y el amor que impone la "madre naturaleza" y la inexorable regla que dicta la convención social.</descripcion>
    </libro>
    <libro>
        <titulo>Nada</titulo>
        <autor>
            <nombre>Carmen</nombre>
            <apellidos>Laforet Díaz</apellidos>
        </autor>
        <genero>Novela</genero>
        <editorial>Ediciones Destino</editorial>
        <fecha>2021-09-01</fecha>
        <ISBN>978-8423359851</ISBN>
        <nPaginas>344</nPaginas>
        <descripcion>Tan solo medio año después de que acabe la guerra civil, la joven Andrea se traslada a Barcelona para estudiar Letras en la universidad. En cuanto entra
            en el piso de su abuela, la suciedad, la tradición, la tensión, la violencia y el odio, un perfecto reflejo de la sociedad de la época, van enturbiando la ilusión que siente por su nueva vida en la Ciudad Condal. Pero cuando conoce a Ena, una chica de la facultad, descubre un mundo brillante y esperanzador y se da cuenta de que la ansiada libertad que persigue está más cerca de lo que cree.
            
            Con una sensibilidad extraordinaria para adentrarse en los recovecos más íntimos del alma humana, Carmen Laforet retrata las vivencias de una mujer que, ante una realidad cruel y opresiva, no desiste de su empeño por ser quien quiere ser.
