=== vchacal327/VictorChacon_UD4_LMSGI/Clientes/Gestoria.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="gestoria">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="alta" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="sede">
                                <xs:complexType>
                                        <xs:sequence>
                                            <xs:element type="xs:string" name="nombEmpleado"/>
                                            <xs:element type="xs:date" name="fecha"/>
                                        </xs:sequence>
                                    <xs:attribute type="xs:string" name="codigo" use="required"/>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="cliente">
                                <xs:complexType>
                                        <xs:sequence>
                                            <xs:element type="xs:string" name="descCliente"/>
                                            <xs:element type="xs:integer" name="numero"/>
                                            <xs:element name="vivienda" minOccurs="1" maxOccurs="unbounded">
                                                <xs:complexType>
                                                        <xs:sequence>
                                                            <xs:element type="xs:integer" name="coste"/>
                                                            <xs:element type="xs:string" name="resumen"/>
                                                            <xs:element type="xs:integer" name="plazo"/>
                                                        </xs:sequence>
                                                    <xs:attribute type="xs:string" name="ID" use="required"/>
                                                </xs:complexType>
                                            </xs:element>
                                        </xs:sequence>
                                    <xs:attribute type="xs:string" name="codigo" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== vchacal327/VictorChacon_UD4_LMSGI/Clientes/Gestoria_X.xml
<?xml version="1.0" encoding="UTF-8"?>
<gestoria xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Gestoria.xsd">
    <alta>
        <sede codigo="SEV-110">
            <nombEmpleado>Pedro Gómez</nombEmpleado>
            <fecha>2008-07-11</fecha>
        </sede>
        <cliente codigo="AND-45">
            <descCliente>Solvente</descCliente>
            <numero>2</numero>
            <vivienda ID="001">
                <coste>50000</coste>
                <resumen>Edificio en mejorables condiciones, aunque sin peligro.</resumen>
                <plazo>20</plazo>
            </vivienda>
            <vivienda ID="002">
                <coste>28000</coste>
                <resumen>Pequeño apartamento, bien ubicado y limpio.</resumen>
                <plazo>45</plazo>
            </vivienda>
        </cliente>
    </alta>
    <alta>
        <sede codigo="CDZ-100">
            <nombEmpleado>Luisa Romero</nombEmpleado>
            <fecha>2010-09-17</fecha>
        </sede>
        <cliente codigo="AND-731">
            <descCliente>Insolvente</descCliente>
            <numero>1</numero>
            <vivienda ID="010">
                <coste>7000</coste>
                <resumen>Poco espaciosa y muy descuidada.</resumen>
                <plazo>30</plazo>
            </vivienda>
        </cliente>
    </alta>
    <alta>
        <sede codigo="HLV-140">
            <nombEmpleado>Nagore Suárez</nombEmpleado>
            <fecha>2015-01-24</fecha>
        </sede>
        <cliente codigo="AND-548">
            <descCliente>Solvente</descCliente>
            <numero>3</numero>
            <vivienda ID="011">
                <coste>70000</coste>
                <resumen>Problemas con sistema de tuberías, el resto bien.</resumen>
                <plazo>30</plazo>
            </vivienda>
            <vivienda ID="022">
                <coste>280000</coste>
                <resumen>Piso grande con buen cuidado.</resumen>
                <plazo>90</plazo>
            </vivienda>
            <vivienda ID="044">
                <coste>145000</coste>
                <resumen>Casa de campo con piscina.</resumen>
                <plazo>45</plazo>
            </vivienda>
        </cliente>
    </alta>
    <alta>
        <sede codigo="CDZ-100">
            <nombEmpleado>José Luis Pérez</nombEmpleado>
            <fecha>2003-06-23</fecha>
        </sede>
        <cliente codigo="AND-090">
            <descCliente>Solvente</descCliente>
            <numero>1</numero>
            <vivienda ID="072">
                <coste>100000</coste>
                <resumen>Dúplex a las afueras de la localidad.</resumen>
                <plazo>40</plazo>
            </vivienda>
        </cliente>
    </alta>
    <alta>
        <sede codigo="ALM-150">
            <nombEmpleado>Ramón Soroya</nombEmpleado>
            <fecha>2011-04-09</fecha>
        </sede>
        <cliente codigo="AND-243">
            <descCliente>Solvente</descCliente>
            <numero>1</numero>
            <vivienda ID="019">
                <coste>94000</coste>
                <resumen>Casa de campo algo descuidada.</resumen>
                <plazo>30</plazo>
            </vivienda>
        </cliente>
    </alta>
    <alta>
        <sede codigo="SEV-110">
            <nombEmpleado>Mónica Naranjo</nombEmpleado>
            <fecha>2014-12-11</fecha>
        </sede>
        <cliente codigo="AND-089">
            <descCliente>Insolvente</descCliente>
            <numero>2</numero>
            <vivienda ID="017">
                <coste>5000</coste>
                <resumen>Pequeño cobertizo con tejado de chapa. En malas condiciones.</resumen>
                <plazo>20</plazo>
            </vivienda>
            <vivienda ID="081">
                <coste>24000</coste>
                <resumen>Casa antigua con peligro de derrumbe.</resumen>
                <plazo>15</plazo>
            </vivienda>
        </cliente>
    </alta>
    <alta>
        <sede codigo="GRN-130">
            <nombEmpleado>Jesús Mario Moreno</nombEmpleado>
            <fecha>2010-01-30</fecha>
        </sede>
        <cliente codigo="AND-098">
            <descCliente>Solvente</descCliente>
            <numero>1</numero>
            <vivienda ID="005">
                <coste>187000</coste>
                <resumen>Casa unifamiliar en perfectas condiciones (nueva).</resumen>
                <plazo>60</plazo>
            </vivienda>
        </cliente>
    </alta>
    <alta>
        <sede codigo="MLG-120">
            <nombEmpleado>Juana María López</nombEmpleado>
            <fecha>2004-10-27</fecha>
        </sede>
        <cliente codigo="035">
            <descCliente>Solvente</descCliente>
            <numero>1</numero>
            <vivienda ID="097">
                <coste>360000</coste>
                <resumen>Chalé adosado no muy espacioso pero confortable.</resumen>
                <plazo>45</plazo>
            </vivienda>
        </cliente>
    </alta>
    <alta>
        <sede codigo="CDB-160">
            <nombEmpleado>Paula Amaya</nombEmpleado>
            <fecha>2009-11-25</fecha>
        </sede>
        <cliente codigo="AND-140">
            <descCliente>Solvente</descCliente>
            <numero>2</numero>
            <vivienda ID="076">
                <coste>200000</coste>
                <resumen>Problema con el cuadro eléctrico.</resumen>
                <plazo>30</plazo>
            </vivienda>
            <vivienda ID="043">
                <coste>50000</coste>
                <resumen>Pequeño piso con 1 habitación.</resumen>
                <plazo>40</plazo>
            </vivienda>
        </cliente>
    </alta>
    <alta>
        <sede codigo="CDZ-100">
            <nombEmpleado>Jorge Suleiman</nombEmpleado>
            <fecha>2014-06-13</fecha>
        </sede>
        <cliente codigo="AND-120">
            <descCliente>Insolvente</descCliente>
            <numero>1</numero>
            <vivienda ID="088">
                <coste>140000</coste>
                <resumen>Apartamento estrecho y con múltiples problemas estructurales.</resumen>
                <plazo>20</plazo>
            </vivienda>
        </cliente>
    </alta>
</gestoria>
